[project]
name = "tqdm-menu-bar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rumps>=0.4.0",
    "tqdm>=4.67.0",
]
[tool.uv]
dev-dependencies = [
  "fonttools",
]
