[project]
name = "mtqdm"
version = "0.1.1"
description = "Put tqdm on your menu bar."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rumps>=0.4.0",
    "tqdm>=4.67.0",
]
[tool.uv]
dev-dependencies = [
  "fonttools",
]
